version: "3.7"
services:
  db:
    image: "postgres"
    volumes:
      - "data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "PGDATA=/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: "."
    image: "todo_app:latest"
    restart: "always"
    ports:
      - "8000:8000"
    volumes:
      - ".:/usr/src/app"
    environment:
      - "DB_HOST=db"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
    command: bash -c "python3 manage.py runserver [::]:8000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  redis:
   image: 'bitnami/redis:latest'
   ports:
     - '6379:6379'
   environment:
     - ALLOW_EMPTY_PASSWORD=yes
   depends_on:
     - "web"

  celery:
   image: "todo_app:latest"
   restart: "always"
   volumes:
     - ".:/usr/src/app"
   command: bash -c "celery -A todo_app worker -l INFO"
   depends_on:
     - "redis"

volumes:
  data:
    driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /disk1/prometheus-data
